name: Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Testy Jednostkowe
        run: npm test  
      - name: Testy E2E Cypress
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3
      
      - name: Podłącz SSH i wdróż
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd ~/todoapp
            git pull origin master
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d