name: Deploy to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pymongo schedule pytest pytest-mock
      - name: Testy Jednostkowe (Pytest)
        run: pytest test_unit.py
      - name: Testy Jednostkowe JS (Jest)
        run: |
          npm install
          npm test

      - name: Testy E2E Cypress
        uses: cypress-io/github-action@v7
        with:
          start: python app.py
          wait-on: 'http://localhost:5000'
        env:
          GMAIL_USER: test@gmail.com
          GMAIL_PASSWORD: fake_password
          MONGO_URL: mongodb://localhost:27017/todoapp
          
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Pobierz kod
        uses: actions/checkout@v3
      
      - name: Podłącz SSH i wdróż
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd ~/todoapp
            git pull origin master
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d